#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0 on Fri Sep 27 21:20:22 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.x = ""
        self.y = ""
        self.op =""

        self.SetSize((400, 300))
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")

        self.button_1 = wx.Button(self, wx.ID_ANY, "1")
        self.button_1.Bind(wx.EVT_BUTTON, self.Button1)

        self.button_2 = wx.Button(self, wx.ID_ANY, "2")
        self.button_2.Bind(wx.EVT_BUTTON, self.Button2)

        self.button_3 = wx.Button(self, wx.ID_ANY, "3")
        self.button_3.Bind(wx.EVT_BUTTON, self.Button3)

        self.button_div = wx.Button(self, wx.ID_ANY, "/")
        self.button_div.Bind(wx.EVT_BUTTON, self.ButtonDiv)

        self.button_4 = wx.Button(self, wx.ID_ANY, "4")
        self.button_4.Bind(wx.EVT_BUTTON, self.Button4)

        self.button_5 = wx.Button(self, wx.ID_ANY, "5")
        self.button_5.Bind(wx.EVT_BUTTON, self.Button5)

        self.button_6 = wx.Button(self, wx.ID_ANY, "6")
        self.button_6.Bind(wx.EVT_BUTTON, self.Button6)

        self.button_mul = wx.Button(self, wx.ID_ANY, "*")
        self.button_mul.Bind(wx.EVT_BUTTON, self.ButtonMul)

        self.button_7 = wx.Button(self, wx.ID_ANY, "7")
        self.button_7.Bind(wx.EVT_BUTTON, self.Button7)

        self.button_8 = wx.Button(self, wx.ID_ANY, "8")
        self.button_8.Bind(wx.EVT_BUTTON, self.Button8)

        self.button_9 = wx.Button(self, wx.ID_ANY, "9")
        self.button_9.Bind(wx.EVT_BUTTON, self.Button9)

        self.button_sub = wx.Button(self, wx.ID_ANY, "-")
        self.button_sub.Bind(wx.EVT_BUTTON, self.ButtonSub)

        self.button_dot = wx.Button(self, wx.ID_ANY, ".")
        self.button_dot.Bind(wx.EVT_BUTTON, self.ButtonDot)

        self.button_0 = wx.Button(self, wx.ID_ANY, "0")
        self.button_0.Bind(wx.EVT_BUTTON, self.Button0)

        self.button_eq = wx.Button(self, wx.ID_ANY, "=")
        self.button_eq.Bind(wx.EVT_BUTTON, self.ButtonEqu)

        self.button_add = wx.Button(self, wx.ID_ANY, "+")
        self.button_add.Bind(wx.EVT_BUTTON, self.ButtonAdd)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Calculator")
        self.text_ctrl_1.SetMinSize((500, 29))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(0, 4, 1, 1)
        sizer_1.Add(self.text_ctrl_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_2, 0, 0, 0)
        grid_sizer_1.Add(self.button_3, 0, 0, 0)
        grid_sizer_1.Add(self.button_div, 0, 0, 0)
        grid_sizer_1.Add(self.button_4, 0, 0, 0)
        grid_sizer_1.Add(self.button_5, 0, 0, 0)
        grid_sizer_1.Add(self.button_6, 0, 0, 0)
        grid_sizer_1.Add(self.button_mul, 0, 0, 0)
        grid_sizer_1.Add(self.button_7, 0, 0, 0)
        grid_sizer_1.Add(self.button_8, 0, 0, 0)
        grid_sizer_1.Add(self.button_9, 0, 0, 0)
        grid_sizer_1.Add(self.button_sub, 0, 0, 0)
        grid_sizer_1.Add(self.button_dot, 0, 0, 0)
        grid_sizer_1.Add(self.button_0, 0, 0, 0)
        grid_sizer_1.Add(self.button_eq, 0, 0, 0)
        grid_sizer_1.Add(self.button_add, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade


    def Button1(self,event):
        self.text_ctrl_1.AppendText("1")

    def Button2(self,event):
        self.text_ctrl_1.AppendText("2")

    def Button3(self,event):
        self.text_ctrl_1.AppendText("3")

    def Button4(self,event):
        self.text_ctrl_1.AppendText("4")

    def Button5(self,event):
        self.text_ctrl_1.AppendText("5")

    def Button6(self,event):
        self.text_ctrl_1.AppendText("6")

    def Button7(self,event):
        self.text_ctrl_1.AppendText("7")

    def Button8(self,event):
        self.text_ctrl_1.AppendText("8")

    def Button9(self,event):
        self.text_ctrl_1.AppendText("9")

    def Button0(self,event):
        self.text_ctrl_1.AppendText("0")

    def ButtonDot(self,event):
        self.text_ctrl_1.AppendText(".")

    def ButtonAdd(self,event):
        self.x = self.text_ctrl_1.GetValue()
        self.text_ctrl_1.Clear()
        self.op = self.button_add.GetLabelText()

    def ButtonSub(self,event):
        self.x = self.text_ctrl_1.GetValue()
        self.text_ctrl_1.Clear()
        self.op = self.button_sub.GetLabelText()

    def ButtonMul(self,event):
        self.x = self.text_ctrl_1.GetValue()
        self.text_ctrl_1.Clear()
        self.op = self.button_mul.GetLabelText()

    def ButtonDiv(self,event):
        self.x = self.text_ctrl_1.GetValue()
        self.text_ctrl_1.Clear()
        self.op = self.button_div.GetLabelText()

    
    def ButtonEqu(self,event):
        
        self.y = self.text_ctrl_1.GetValue()
        self.text_ctrl_1.Clear()
        if self.op == "+":
            r = float(self.x) + float(self.y)
            self.text_ctrl_1.SetValue(str(r))

        if self.op == "-":
            r = float(self.x) - float(self.y)
            self.text_ctrl_1.SetValue(str(r))

        if self.op == "*":
            r = float(self.x) * float(self.y)
            self.text_ctrl_1.SetValue(str(r))

        if self.op == "/":
            r = float(self.x) / float(self.y)
            self.text_ctrl_1.SetValue(str(r))
            



    
        #wx.MessageBox( "This is a message.", "Button pressed.")
# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.CalcFrame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.CalcFrame)
        self.CalcFrame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    Calulator = MyApp(0)
    Calulator.MainLoop()
